services:
  redis:
    mem_limit: 70m
    memswap_limit: 70m

  rabbitmq:
    mem_limit: 200m
    memswap_limit: 200m

  users:
    mem_limit: 120m
    memswap_limit: 120m

  auctions:
    mem_limit: 120m
    memswap_limit: 120m

  api-gateway:
    mem_limit: 150m
    memswap_limit: 150m
