services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: unless-stopped
    ports:
      - '5672:5672' # AMQP protocol
      - '15672:15672' # management UI
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_ERLANG_COOKIE: 'mysecretcookie'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - auction-net
  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - '6379:6379'
    networks:
      - auction-net

volumes:
  rabbitmq_data:

networks:
  auction-net:
    driver: bridge
