services:
  # 🌐 API Gateway
  - type: web
    name: api-gateway
    env: docker
    rootDir: apps/api-gateway
    plan: free
    autoDeploy: true
    envVars:
      - key: FRONTEND_URL
        value: http://localhost:5174
      - key: GATEWAY_PORT
        value: 3000
      - key: USERS_HOST
        value: users
      - key: USERS_PORT
        value: 3001
      - key: AUCTIONS_HOST
        value: auctions
      - key: AUCTIONS_PORT
        value: 3003
      - key: MONGODB_URI
        value: mongodb+srv://newuser:talJrKdHqv08tyQ0@cluster0.5imn6.mongodb.net/auctions?retryWrites=true&w=majority&appName=Cluster0

  # 👤 Users Service
  - type: web
    name: users
    env: docker
    rootDir: apps/users
    plan: free
    autoDeploy: true
    envVars:
      - key: USERS_PORT
        value: 3001
      - key: MONGODB_URI
        value: mongodb+srv://newuser:talJrKdHqv08tyQ0@cluster0.5imn6.mongodb.net/auctions?retryWrites=true&w=majority&appName=Cluster0

  # 🛒 Auctions Service
  - type: web
    name: auctions
    env: docker
    rootDir: apps/auctions
    plan: free
    autoDeploy: true
    envVars:
      - key: AUCTIONS_PORT
        value: 3002
      - key: MONGODB_URI
        value: mongodb+srv://newuser:talJrKdHqv08tyQ0@cluster0.5imn6.mongodb.net/auctions?retryWrites=true&w=majority&appName=Cluster0
