services:
  # 🌐 API Gateway
  - type: web
    name: api-gateway
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: api-gateway
      - key: FRONTEND_URL
        value: http://localhost:5174
      - key: GATEWAY_PORT
        value: 3000
      - key: USERS_HOST
        value: users
      - key: USERS_PORT
        value: 3001
      - key: AUCTIONS_HOST
        value: auctions
      - key: AUCTIONS_PORT
        value: 3003

  # 👤 Users Service
  - type: web
    name: users
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: users
      - key: USERS_PORT
        value: 3001

  # 🛒 Auctions Service
  - type: web
    name: auctions
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: auctions
      - key: AUCTIONS_PORT
        value: 3003
