apiVersion: apps/v1
kind: Deployment
metadata:
  name: auctions
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auctions
  template:
    metadata:
      labels:
        app: auctions
    spec:
      containers:
        - name: auctions
          image: auctions-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3003
          env:
            - name: NODE_ENV
              value: 'production'
          envFrom:
            - secretRef:
                name: auctions-secrets
