resources:
  - deployment.yaml
  - service.yaml
  - api-gateway-ingress.yaml
  - cluster-issuer.yaml

secretGenerator:
  - name: api-gateway-secrets
    envs:
      - secret.env
generatorOptions:
  disableNameSuffixHash: true
