apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: asia-southeast1-docker.pkg.dev/noted-runway-472014-s2/auctions/users-service:latest
          ports:
            - containerPort: 3001
          env:
            - name: NODE_ENV
              value: 'production'
          envFrom:
            - secretRef:
                name: users-secrets
