apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../gateway
  - ../../users
  - ../../auctions
  - ../../rabbitmq
  - ../../redis

# For Dev environment (Docker desktop or local cluster)
images:
  - name: api-gateway
    newName: dev-registry/api-gateway
    newTag: latest
  - name: users-service
    newName: dev-registry/users-service
    newTag: latest
  - name: auctions-service
    newName: dev-registry/auctions-service
    newTag: latest

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: IfNotPresent
    target:
      kind: Deployment
      name: api-gateway
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: IfNotPresent
    target:
      kind: Deployment
      name: users
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: IfNotPresent
    target:
      kind: Deployment
      name: auctions
